[mypy]
python_version = 3.11
strict = True
warn_unreachable = True
warn_unused_ignores = True
show_error_codes = True
files = src

[mypy-gi.*]
ignore_missing_imports = True

[mypy-Xlib.*]
ignore_missing_imports = True
